---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    - htop-osx
    - watch
    - rsync
    - git-flow
    - git
    - git-extras
    - bash-completion
